Upgrade ovs to 2.11.0 to be DPDK 18.x compatible
After upgrading  DPDK to dpdk-18.11-2.el7_6.x86_64, ovs 2.10.0 fails
fails to install at multiple missing libraries

Error: Package: 1:openvswitch-2.10.1-1.el7.x86_64 (delorean-master-deps)
           Requires: librte_bus_pci.so.1()(64bit)
           Available: dpdk-17.11-13.el7.x86_64 (quickstart-centos-extras)
               librte_bus_pci.so.1()(64bit)
           Available: dpdk-17.11-15.el7.x86_64 (quickstart-centos-extras)
               librte_bus_pci.so.1()(64bit)
           Installing: dpdk-18.11-2.el7_6.x86_64 (quickstart-centos-extras)
              ~librte_bus_pci.so.2()(64bit)
Error: Package: 1:openvswitch-2.10.1-1.el7.x86_64 (delorean-master-deps)

Change-Id: I57133df0dbcd99d3443cc17b2f5aa0afe49c5999
Related-Bug: #1815863